# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RR1b-AvIyHfF35Ranyu-iv8oSh88yu81
"""

import pandas as pd
import numpy as np
import json
import tensorflow as tf
from sklearn.model_selection import train_test_split
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense, Dropout
from google.colab import files

# Load & prepare Kaggle dataset
df = pd.read_csv('spam.csv', encoding='latin-1')[['v1', 'v2']]
df.columns = ['label', 'message']
df['label'] = df['label'].map({'spam': 1, 'ham': 0})

# Load Indian dataset
df_indian = pd.read_csv('spam_ham_india.csv', encoding='latin-1')
df_indian.columns = ['message', 'label']
df_indian['label'] = df_indian['label'].map({'spam': 1, 'ham': 0})

# Load extra Indian SMS
df_extra = pd.read_csv('indian_sms_extra.csv')
df_extra['label'] = df_extra['label'].map({'spam': 1, 'ham': 0})

# Combine all 3 datasets
df_final = pd.concat([df, df_indian, df_extra], ignore_index=True).dropna()
print(f"Total SMS: {len(df_final)}")
print(df_final['label'].value_counts())

# Tokenize
tokenizer = Tokenizer(num_words=5000, oov_token='<OOV>')
tokenizer.fit_on_texts(df_final['message'])
X = np.array(pad_sequences(tokenizer.texts_to_sequences(df_final['message']), maxlen=100, truncating='post'))
y = np.array(df_final['label'])

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Build & train
model = Sequential([
    Embedding(5000, 64),
    LSTM(64),
    Dropout(0.5),
    Dense(1, activation='sigmoid')
])

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
model.fit(X_train, y_train, epochs=10, validation_data=(X_test, y_test))

loss, accuracy = model.evaluate(X_test, y_test)
print(f"Final Accuracy: {accuracy * 100:.2f}%")

# Save TFLite
converter = tf.lite.TFLiteConverter.from_keras_model(model)
converter.target_spec.supported_ops = [
    tf.lite.OpsSet.TFLITE_BUILTINS,
    tf.lite.OpsSet.SELECT_TF_OPS
]
converter._experimental_lower_tensor_list_ops = False
with open('sms_model.tflite', 'wb') as f:
    f.write(converter.convert())
print("sms_model.tflite saved!")

# Save tokenizer
with open('tokenizer.json', 'w') as f:
    json.dump(tokenizer.to_json(), f)
print("tokenizer.json saved!")

# Auto download
files.download('sms_model.tflite')
files.download('tokenizer.json')
print("Both files downloaded!")

from google.colab import drive
drive.mount('/content/drive')