// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDT0Jm6BzuaS14LuUKlJoLJIq5oQrjrzeM',
    appId: '1:339920863112:web:29288f34deb61b323d443d',
    messagingSenderId: '339920863112',
    projectId: 'cybershield-6388c',
    authDomain: 'cybershield-6388c.firebaseapp.com',
    storageBucket: 'cybershield-6388c.firebasestorage.app',
    measurementId: 'G-ZXJSRDWKJ4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7seXqyDI8pWRvaFiQv-KTjW00tis1RnQ',
    appId: '1:339920863112:android:d11a247a0d8157663d443d',
    messagingSenderId: '339920863112',
    projectId: 'cybershield-6388c',
    storageBucket: 'cybershield-6388c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0d6x7XcJ32Q6MS4AAcG4zqtZ3hp4YhzQ',
    appId: '1:339920863112:ios:627dde6a41bc38823d443d',
    messagingSenderId: '339920863112',
    projectId: 'cybershield-6388c',
    storageBucket: 'cybershield-6388c.firebasestorage.app',
    iosBundleId: 'com.example.cyberShield',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0d6x7XcJ32Q6MS4AAcG4zqtZ3hp4YhzQ',
    appId: '1:339920863112:ios:627dde6a41bc38823d443d',
    messagingSenderId: '339920863112',
    projectId: 'cybershield-6388c',
    storageBucket: 'cybershield-6388c.firebasestorage.app',
    iosBundleId: 'com.example.cyberShield',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDT0Jm6BzuaS14LuUKlJoLJIq5oQrjrzeM',
    appId: '1:339920863112:web:ef68ebae0cf4cc693d443d',
    messagingSenderId: '339920863112',
    projectId: 'cybershield-6388c',
    authDomain: 'cybershield-6388c.firebaseapp.com',
    storageBucket: 'cybershield-6388c.firebasestorage.app',
    measurementId: 'G-6F05KK50PE',
  );
}
